### ISSUE TITLE
G2 task assignments for HW.

### ISSUE THREAD

**Issue by Pranjal-Srivastava-2023** [ubsuny/23-Homework1G2#11]
@s4il3sh @tirthbha Please discuss which task are you going to undertake. I will take care of the Algorithm and coding.

1. Algorithm and coding- @Pranjal-Srivastava-2023 
2. Unit Test- ?
3. Documentation- ?

**Comment by tirthbha** [comment]
We will let you know tomorrow after some discussion among us. I want to know a brief information about this task then I will go for it. Thank you!

**Comment by s4il3sh** [comment]
@Pranjal-Srivastava-2023 documentation it is! Shall i write documentation creating .md file or write along the python code.

**Comment by Pranjal-Srivastava-2023** [comment]
> @Pranjal-Srivastava-2023 documentation it is! Shall i write documentation creating .md file or write along the python code?

@s4il3sh that's great! We need to create documentation as a markdown file i.e with extension .md
