### ISSUE TITLE
Documentation help needed..

### ISSUE THREAD

**Issue by uarif** [ubsuny/23-Homework1G2#20]
Hello group 2, I am asking about the documentation, in documentation, one is supposed to explain what did they do, and how did they do?
Thank you.

**Comment by s4il3sh** [comment]
@uarif it's about the code you implemented. You need to describe the code and its function and what parameters are required to run the code.

**Comment by Pranjal-Srivastava-2023** [comment]
> Hello group 2, I am asking about the documentation, in documentation, one is supposed to explain what did they do, and how did they do? Thank you.

@uarif Yes! That is correct. In documentation, we need to explain what our code is doing, what algorithm we implemented, what modules we imported from the python library e.t.c.

**Comment by poojashresthacode** [comment]
Are we using markdown for this? and are we copying the material of our markdown to our repo? Is this what we are supposed to do?

**Comment by uarif** [comment]
What, I am going to do is, just to create documentation file and explain our code and its purpose. I don't know if we are supposed to copy anything. You can double-check with anyone else, too.

**Comment by Pranjal-Srivastava-2023** [comment]
> Are we using markdown for this? and are we copying the material of our markdown to our repo? Is this what we are supposed to do?

@poojashresthacode we will create a branch of our repository and then add the markdown file to this branch. In this markdown file, we will document everything. Once this is done, we will merge the branch to our main repository.
