### ISSUE TITLE
G2 Unit Test

### ISSUE THREAD

**Issue by tirthbha** [ubsuny/23-Homework1G2#24]
Can I initiate unit test by using just two elements of the circuit? What explanations should be required for the results?
"Suppose for 1+0=1,  the probability associated with measuring outcome 1 is higher than the probability associated with measuring outcome 0. Therefore, the bar for outcome 1 is taller than the bar for outcome 0, indicating a higher likelihood of measuring 1 as the result." Is this the correct way to explain about the nature of graph?

**Comment by yasmensarhan27** [comment]
we, in G4,  have the same problem for the multiplication. we are stuck in how to test our implementation.

**Comment by yasmensarhan27** [comment]
but you can perform the same as the professor 
your truth table will be as follows:

**Comment by yasmensarhan27** [comment]
![IMG_7830](https://github.com/ubsuny/23-Homework1G2/assets/38404107/de4bba22-2cc4-406e-9bce-b204275a219f)

**Comment by s4il3sh** [comment]
@tirthbha @yasmensarhan27 To test the code you need to install qiskit in the jupyter notebook and run it. If your code works perfectly, you will see output else it throws some errors.

**Comment by Pranjal-Srivastava-2023** [comment]
@tirthbha the unit test is done. In the documentation, I have added circuits for 1+1 and 1+0 they give correct results. But, you can try running quantum_addition.py in IBM Lab and run it for different numbers. Does the code fails for some numbers?

**Comment by tirthbha** [comment]
> @tirthbha the unit test is done. In the documentation, I have added circuits for 1+1 and 1+0 they give correct results. But, you can try running quantum_addition.py in IBM Lab and run it for different numbers. Does the code fails for some numbers?
You mean I have to check through code or through circuit elements?

**Comment by Pranjal-Srivastava-2023** [comment]
> > @tirthbha the unit test is done. In the documentation, I have added circuits for 1+1 and 1+0 they give correct results. But, you can try running quantum_addition.py in IBM Lab and run it for different numbers. Does the code fails for some numbers?
> 
> You mean I have to check through code or through circuit elements?

Check through the code now. I already checked with the circuits.

**Comment by Pranjal-Srivastava-2023** [comment]
@tirthbha let us know the results here so we can add in the documentation.

**Comment by tirthbha** [comment]
> @tirthbha let us know the results here so we can add in the documentation.

Sure, I will go through it and will post here as soon as possible.

**Comment by tirthbha** [comment]
@Pranjal-Srivastava-2023  To assign label,  I might have the necessary permissions (e.g., write access) to the repository. I mean, I won't be able to assign labels without maintainer's permission.

**Comment by tirthbha** [comment]
> @tirthbha let us know the results here so we can add in the documentation.

Even though the code is designed to add two numbers using a quantum circuit. However, it is not working  correctly for certain input numbers, 
For examples:
7 + 7 = 10
1 + 15 = 12
7 + 9 = 0
15 + 15 = 10
Such discrepancies are due to several reasons:
i) The binary addition of these numbers requires an extra bit for the carry. If the code doesn't account for this properly, it may produce incorrect results.
ii) Even for relatively small numbers, if the quantum circuit has a strict limit on the number of qubits (e.g., 5 qubits), it will fail to represent and compute the sum correctly.
iii) In some cases where one number is significantly smaller than the other, then the code doesn't correctly handle mixed-size inputs, it may produce incorrect results.
iv) If the binary representation of either number exceeds the available qubits, it will cause issues.
v) The binary addition is performed using CNOT gates. If the number of qubits is insufficient to perform the addition, it will result in incorrect or unexpected behavior.

**Comment by tirthbha** [comment]
This part is done!
