### ISSUE TITLE
Can not add group members (Group-2).

### ISSUE THREAD

**Issue by Pranjal-Srivastava-2023** [ubsuny/23-Homework1G2#3]
My group member's usernames are:

1. tirthbha
2. s4il3sh

**Comment by laserlab** [comment]
I added them. Let me know if it works and then close this issue

**Comment by Pranjal-Srivastava-2023** [comment]
It is still not working professor. I can not access the collaborators setting nor can I view the team members in the community section.

**Comment by laserlab** [comment]
As described in the linked issue of group 1 maintainers cannot access collaborators settings, that’s why I did that for you. A good test would be if your team members can open issues. That should work now. THey are part of the team @HW1G2_CP23-1 in case that shows up in the community section. Also one member @tirthbha did not accept the invite yet.

**Comment by laserlab** [comment]
Btw. You can use mentions like @Pranjal-Srivastava-2023 or @s4il3sh to directly access them or the team @ubsuny/hw1g1_cp23-1

**Comment by Pranjal-Srivastava-2023** [comment]
Thank you, professor. It works, @s4il3sh can open issues now, and @tirthbha has yet to accept the invite. I am closing the issue.
