### ISSUE TITLE
No docstring in trial_code.py

### ISSUE THREAD

**Issue by JustinJaniszewski** [ubsuny/23-Homework1G2#31]
I've also realized you do not include a docstring to your code. This may look something like this:

```
def my_function(x, y):
  """This function adds two numbers together.

  Args:
    x: The first number.
    y: The second number.

  Returns:
    The sum of x and y.
  """

  return x + y
```

**Comment by JustinJaniszewski** [comment]
I've canceled the old merge request that I talked about in #30 , committed a docstring, and did a new merge requst.

**Comment by Pranjal-Srivastava-2023** [comment]
@JustinJaniszewski thank you. I have merged your request.
