### ISSUE TITLE
Branch in main repo

### ISSUE THREAD

**Issue by reshnashrestha** [ubsuny/23-Homework1G2#38]
Hey @WildJimmy @Pranjal-Srivastava-2023, I believe you guys can understand this. I created a branch and an md file in my forked repository. After that, I pulled and merged the request from the forked repo to the main HW one. The thing is that the md file is now shown on the main homework repo of our group but my branch is not there while it is in my fork repo. What is the issue with the branch?

**Comment by Pranjal-Srivastava-2023** [comment]
@reshnashrestha If the branch you created in your forked repository was deleted after the pull request was merged, it won't appear in the main repository. GitHub typically deletes the source branch of a pull request in the forked repository after it's merged to keep things clean. This is the default behavior. 

To be double-sure, first, ensure that your pull request has been merged. If it has and you're still not seeing the branch in the main repository, it's possible that the branch was deleted in your forked repository after the merge. In that case, you may need to recreate the branch and make a new pull request if further changes are needed in the main repository.

**Comment by reshnashrestha** [comment]
@Pranjal-Srivastava-2023 the branch is still in my forked repo. That is where I got caught up 
![image](https://github.com/ubsuny/23-Homework1G2/assets/143649458/91e6052c-ceb7-4e3e-b17b-afaf2cc0a2b5)

**Comment by reshnashrestha** [comment]
I think it's like only the maintainer's branches are showing up in the homework main repository after merging .. whilst the merge requests made by other group members are not showing up in the main branch even though the changes appear in the main branch. This might be the default setting in our homework main repo. And to check up on how many branches are made by members, we can always check on the forked repo.
