### ISSUE TITLE
Division function using qiskit 

### ISSUE THREAD

**Issue by pratibha77118** [ubsuny/23-Homework1G2#39]
Hello, [23-Homework1G2] 
I am wondering if division function is possible to implement? I got to know it is quite complex to run division function in Quantam computer ( from ChatGpt). If you have any idea please assist us to start with this.

**Comment by s4il3sh** [comment]
@pratibha77118 well, if you can multiply two numbers, the division is possible I guess. The division is based on multiplication. Multiply one number and inverse of another number. If could create a code to inverse the other number and multiply them using AND gate. I guess that will work. (It is based on my assumption not done it actually).
