### ISSUE TITLE
Including circuits in the documentation file..

### ISSUE THREAD

**Issue by uarif** [ubsuny/23-Homework1G2#40]
Hi group #2. Your documentation files seems very detailed, I liked it. But is it mandatory to add the circuit etc. in the documentation file?
Thank you.

**Comment by Pranjal-Srivastava-2023** [comment]
@uarif we are still working on documentation it is not complete yet. Adding circuits is not mandatory. We have added circuits because they are simple in the case of "addition." For other operators, I think it will be tough.

**Comment by uarif** [comment]
Thank you.
