### ISSUE TITLE
Code running in local and quantum computer

### ISSUE THREAD

**Issue by reshnashrestha** [ubsuny/23-Homework1G2#41]
Have you tried running the quantum_addition.py file in your local and IMB quantum composer? 
If yes, will you please elaborate on this from the initial steps we need to execute?

**Comment by Pranjal-Srivastava-2023** [comment]
@reshnashrestha we ran circuits designed using composer on IBM Quantum computer. For running quantum_addition.py we just used IBM Lab. We are now trying to get quantum_addition.py to run on some cloud-based quantum computer.

**Comment by reshnashrestha** [comment]
Do you have any idea on how to run locally using the API key and then try to access the quantum computer lab?

**Comment by s4il3sh** [comment]
@reshnashrestha there is a Qiskit platform to test your code which simulates the results operated by a quantum computer (locally).

**Comment by reshnashrestha** [comment]
Thank you @Pranjal-Srivastava-2023 and @s4il3sh
