### ISSUE TITLE
Why there is showing "This branch has conflicts that must be resolved"

### ISSUE THREAD

**Issue by tirthbha** [ubsuny/23-Homework1G2#42]
Why there is showing "This branch has conflicts that must be resolved"

_Originally posted by @tirthbha in https://github.com/ubsuny/23-Homework1G2/issues/25#issuecomment-1722280175_

**Comment by Pranjal-Srivastava-2023** [comment]
This is because two different branches made changes in the same line of code. So, only one can be approved.
