### ISSUE TITLE
Testing your code..

### ISSUE THREAD

**Issue by uarif** [ubsuny/23-Homework1G2#43]
On what platform do you guys are checking your code if It's working or not?

**Comment by tirthbha** [comment]
> On what platform do you guys are checking your code if It's working or not?
 
I am using anaconda python tool to check whether it is working or not.

**Comment by Pranjal-Srivastava-2023** [comment]
You can just use IBM Quantum Learning Lab for testing.

**Comment by s4il3sh** [comment]
@uarif In my case I am using Jupyter Notebook with Qiskit installed on it. Since the code is based on the Qiskit platform, I guess that would do a good job.

**Comment by AhmedCode99** [comment]
I am using google colab
