### ISSUE TITLE
Encoding Input

### ISSUE THREAD

**Issue by pratibha77118** [ubsuny/23-Homework1G2#47]
Hi [23-Homework1G2],
I would like to know how you have done input encoding for your quantam operation. As we have to assign classical numbers to quantam state in qiskit. Please assist us in doing this. I want to convert number 4 to quantam state so that I can do division operation using it.

**Comment by s4il3sh** [comment]
@pratibha77118  If you see our code (quantum_addition), in the following part:

# Determine the number of qubits needed to represent the numbers
max_value = max(number1, number2)
num_qubits = max(1, (max_value.bit_length() + 1))

# Create a quantum circuit with enough qubits
qc = QuantumCircuit(num_qubits * 2, num_qubits)

# Encode the classical numbers into quantum states
for i in range(num_qubits):
    if (number1 >> i) & 1:
        qc.x(i)  # Apply X gate for 1 bits in number1
    if (number2 >> i) & 1:
        qc.x(i + num_qubits)  # Apply X gate for 1 bits in number2

It does the conversion job from classical numbers to qubits.

**Comment by pratibha77118** [comment]
Thanks for your help @s4il3sh. However, I am finding difficult encode number with more than 1 bits as we have to assign all our input in same bits.
