### ISSUE TITLE
Milestone in Progress?

### ISSUE THREAD

**Issue by s4il3sh** [ubsuny/23-Homework1G2#48]
HI G2 Team,

So we created milestone which means progress are tracked. It shows 0% work done. Could you @Pranjal-Srivastava-2023 update on what work has been done and what's left? So that we can manage our tasks.

**Comment by Pranjal-Srivastava-2023** [comment]
@s4il3sh we need to finalize the documentation. Add Tirth's unit test to the documentation.md
