### ISSUE TITLE
Need to add Tirth's unit test section in documentation.md

### ISSUE THREAD

**Issue by Pranjal-Srivastava-2023** [ubsuny/23-Homework1G2#49]
@s4il3sh can you take care of this?

**Comment by tirthbha** [comment]
@Pranjal-Srivastava-2023 I have already done some of my unit test activities by checking: which numbers fail to work in the code. Added to issue #24

**Comment by Pranjal-Srivastava-2023** [comment]
@tirthbha that's great! Send me the merge request when done.

**Comment by s4il3sh** [comment]
do we need to create documentation for full-adder too? just like we did in the half-adder..

**Comment by tirthbha** [comment]
> @tirthbha that's great! Send me the merge request when done.

@Pranjal-Srivastava-2023  I have added the explanation to the md file and I have sent you a merge request.

**Comment by tirthbha** [comment]
> do we need to create documentation for full-adder too? just like we did in the half-adder..
 @s4il3sh I think we are not going to do that now, as it requires much time to complete the task.

**Comment by s4il3sh** [comment]
I think it is done!
