### ISSUE TITLE
so guys, which arithmetic function are you gonna implement on IBM QC?

### ISSUE THREAD

**Issue by s4il3sh** [ubsuny/23-Homework1G2#5]
Lets discuss about it.

**Comment by Pranjal-Srivastava-2023** [comment]
I think implementing addition or subtraction on a quantum computer would be a good starting point. Let's do a bit of research about what algorithm to use on IBM QC and how is it different from running a code on a classical computer. Then we can distribute the tasks among ourselves. What do you think?

**Comment by s4il3sh** [comment]
Well, I don't think we could directly implement our Python code on the QC. We need to run the Qiskit code based on Python to use QC. Let me know if that works.

**Comment by tirthbha** [comment]
Actually, I am the beginner to this field, so it will take a bit time to understand about the topic.

**Comment by s4il3sh** [comment]
> Actually, I am the beginner to this field, so it will take a bit time to understand about the topic.

@tirthbha No problem. Take your time!

**Comment by tirthbha** [comment]
> I think implementing addition or subtraction on a quantum computer would be a good starting point. Let's do a bit of research about what algorithm to use on IBM QC and how is it different from running a code on a classical computer. Then we can distribute the tasks among ourselves. What do you think?

Sure!

**Comment by reshnashrestha** [comment]
Hi guys, I saw that you are planning on addition or subtraction, I think we G3 will be doing addition, so please update us on what you decided. Thanks in advance.

**Comment by Pranjal-Srivastava-2023** [comment]
@s4il3sh @tirthbha I have looked at the basic idea behind the implementation of a classical operation on a Quantum Computer. I had ChatGPT summarize it for us below. Let's go with the addition operator, it is apparently the simplest so we can understand the concept better.

1. **Quantum Circuit:** Think of a quantum circuit as a set of instructions for the quantum computer. Just like a recipe guides a chef in the kitchen, a quantum circuit guides the quantum computer in performing specific tasks.
2. **Encoding:** When you want to add two numbers, the first step is to encode these numbers into a quantum state. This is like translating the numbers into a language that the quantum computer understands. If you have the numbers 3 and 2, you would represent them as a set of qubits in a specific way.
3. **Quantum Addition:** The heart of the process involves performing addition using quantum gates and operations. This step is where the quantum magic happens. Quantum gates are like specialized tools that the quantum computer uses to manipulate the qubits in a way that simulates addition.
4. **Measurement:** After the quantum addition, we need to find out the result. Measurement is the process of checking what the qubits look like after the quantum operations. The result is often probabilistic, meaning there can be multiple possible outcomes.
5. **Simulation or Real Quantum Computer**: At this stage, you decide whether to run the code on a quantum simulator (a software-based quantum computer emulator) or on a real quantum computer. Simulators are like virtual quantum computers, while real quantum computers are physical machines designed to perform quantum computations.
6. **Execution:** If you choose a quantum simulator, you run your quantum circuit on it. If you choose a real quantum computer, you send your quantum circuit to the machine for execution.
7. **Result:** After execution, you receive a result. In the case of addition, this result represents the sum of the two numbers you encoded in the beginning.

**Comment by Pranjal-Srivastava-2023** [comment]
> Hi guys, I saw that you are planning on addition or subtraction, I think we G3 will be doing addition, so please update us on what you decided. Thanks in advance.

@reshnashrestha thanks for letting us know, we are also leaning towards addition.

**Comment by tirthbha** [comment]
> @s4il3sh @tirthbha I have looked at the basic idea behind the implementation of a classical operation on a Quantum Computer. I had ChatGPT summarize it for us below. Let's go with the addition operator, it is apparently the simplest so we can understand the concept better.
> 
>     1. **Quantum Circuit:** Think of a quantum circuit as a set of instructions for the quantum computer. Just like a recipe guides a chef in the kitchen, a quantum circuit guides the quantum computer in performing specific tasks.
> 
>     2. **Encoding:** When you want to add two numbers, the first step is to encode these numbers into a quantum state. This is like translating the numbers into a language that the quantum computer understands. If you have the numbers 3 and 2, you would represent them as a set of qubits in a specific way.
> 
>     3. **Quantum Addition:** The heart of the process involves performing addition using quantum gates and operations. This step is where the quantum magic happens. Quantum gates are like specialized tools that the quantum computer uses to manipulate the qubits in a way that simulates addition.
> 
>     4. **Measurement:** After the quantum addition, we need to find out the result. Measurement is the process of checking what the qubits look like after the quantum operations. The result is often probabilistic, meaning there can be multiple possible outcomes.
> 
>     5. **Simulation or Real Quantum Computer**: At this stage, you decide whether to run the code on a quantum simulator (a software-based quantum computer emulator) or on a real quantum computer. Simulators are like virtual quantum computers, while real quantum computers are physical machines designed to perform quantum computations.
> 
>     6. **Execution:** If you choose a quantum simulator, you run your quantum circuit on it. If you choose a real quantum computer, you send your quantum circuit to the machine for execution.
> 
>     7. **Result:** After execution, you receive a result. In the case of addition, this result represents the sum of the two numbers you encoded in the beginning.

Yes! I also have gone through ChatGPT to get some basic idea about classical algebraic operation on quantum computer. Addition or subtraction is obviously the basis part for us as a first step to get into this world. Let us share an example, if you have found any, so that we could go through its basic idea simultaneously.

**Comment by Pranjal-Srivastava-2023** [comment]
> > @s4il3sh @tirthbha I have looked at the basic idea behind the implementation of a classical operation on a Quantum Computer. I had ChatGPT summarize it for us below. Let's go with the addition operator, it is apparently the simplest so we can understand the concept better.
> > ```
> > 1. **Quantum Circuit:** Think of a quantum circuit as a set of instructions for the quantum computer. Just like a recipe guides a chef in the kitchen, a quantum circuit guides the quantum computer in performing specific tasks.
> > 
> > 2. **Encoding:** When you want to add two numbers, the first step is to encode these numbers into a quantum state. This is like translating the numbers into a language that the quantum computer understands. If you have the numbers 3 and 2, you would represent them as a set of qubits in a specific way.
> > 
> > 3. **Quantum Addition:** The heart of the process involves performing addition using quantum gates and operations. This step is where the quantum magic happens. Quantum gates are like specialized tools that the quantum computer uses to manipulate the qubits in a way that simulates addition.
> > 
> > 4. **Measurement:** After the quantum addition, we need to find out the result. Measurement is the process of checking what the qubits look like after the quantum operations. The result is often probabilistic, meaning there can be multiple possible outcomes.
> > 
> > 5. **Simulation or Real Quantum Computer**: At this stage, you decide whether to run the code on a quantum simulator (a software-based quantum computer emulator) or on a real quantum computer. Simulators are like virtual quantum computers, while real quantum computers are physical machines designed to perform quantum computations.
> > 
> > 6. **Execution:** If you choose a quantum simulator, you run your quantum circuit on it. If you choose a real quantum computer, you send your quantum circuit to the machine for execution.
> > 
> > 7. **Result:** After execution, you receive a result. In the case of addition, this result represents the sum of the two numbers you encoded in the beginning.
> > ```
> 
> Yes! I also have gone through ChatGPT to get some basic idea about classical algebraic operation on quantum computer. Addition or subtraction is obviously the basis part for us as a first step to get into this world. Let us share an example, if you have found any, so that we could go through its basic idea simultaneously.

That's good @tirthbha I do have a working example. It needs to be tested though, I think it doesn't give a correct answer "all the time." Maybe because of probabilistic nature of Quantum Systems? @tirthbha @s4il3sh one of you can do the test and see where the code lacks. If you find a better code please share. I am creating a new issue for this in the repository. Also, check the discussion section, I am cataloging the homework there. It will help with documentation.
