### ISSUE TITLE
Limitation of quantum computers in documentation.md

### ISSUE THREAD

**Issue by Pranjal-Srivastava-2023** [ubsuny/23-Homework1G2#51]
What are the limitations of quantum computers?

**Comment by tirthbha** [comment]
# Limitations of Quantum Computers
Quantum computers, including those used in platforms like IBM Quantum Composer, have several limitations when it comes to designing circuits and solving practical problems. 
i) Error rates: For example, the X gate flips the state of a qubit, changing |0⟩ to |1⟩ and vice versa. Error rates for a gate like the X gate can vary depending on the quantum hardware and environmental conditions.
ii) Gate Errors: Quantum gates are not perfect, and gate errors can accumulate in complex quantum circuits, making it difficult to perform long and accurate computations. 
iii) Limited Software Ecosystem: Quantum software tools and libraries are still in their early stages of development, which can make it challenging for users to design and implement quantum circuits efficiently.
iv) Scalability Challenges: Building large-scale, fault-tolerant quantum computers is a significant engineering challenge. 
v) Qubit Decoherence: Quantum states are fragile and can easily lose their coherence, leading to errors in computations.

**Comment by s4il3sh** [comment]
High cost: Quantum computers are very expensive to build and maintain. This is because they require specialized hardware and operating environments.
Noise and errors: Quantum computers are more prone to noise and errors than traditional computers. This is because qubits are very sensitive to their environment.
Scalability: It is difficult to build and scale quantum computers. This is because qubits are difficult to control and manipulate.
Software development: Developing software for quantum computers is challenging. This is because quantum algorithms are very different from classical algorithms.
Security risks: Quantum computers could be used to break current encryption algorithms. This could pose a threat to data security and privacy.

**Comment by Pranjal-Srivastava-2023** [comment]
@s4il3sh why did you close the issue? This still needs to be added to the documentation.md 
Send me a merge request after adding this to the file documentation.md

**Comment by tirthbha** [comment]
@Pranjal ***@***.***> can you please allow me ti add label to my issues? I can't assign any label to my issues.
________________________________

**Comment by Pranjal-Srivastava-2023** [comment]
@tirthbha please check issue #54 I have commented there. You probably have a pending request for invitation to G2 sent by professor. Once you accept it you should be able to add labels just like @s4il3sh

**Comment by s4il3sh** [comment]
@Pranjal-Srivastava-2023 I don't see this limitation asked in the homework. By the way, the limitation is done I guess. Are you thinking of adding them at the last of the documentation?

**Comment by Pranjal-Srivastava-2023** [comment]
@s4il3sh professor told that we should mention the limitations. For example if we try to build a circuit for adding three digit numbers we will need to define a lot of states which is not practical.

**Comment by s4il3sh** [comment]
@Pranjal-Srivastava-2023 that limitation you mentioned is the same for classical computers too.

**Comment by Pranjal-Srivastava-2023** [comment]
@s4il3sh No! For quantum Computers as the number of qubits increases, the states required to represent them become "exponentially" larger. In classical computers, the states required do not increase "exponentially." We can easily add large numbers using our calculators but it is not possible to do that on a quantum computer.

**Comment by s4il3sh** [comment]
@Pranjal-Srivastava-2023 Great! You may add this point to the last. @tirthbha and me will be working on adding limitation to the documentation.

**Comment by s4il3sh** [comment]
@Pranjal-Srivastava-2023 I guess this is done. I am closing it
