### ISSUE TITLE
how to cancel pull request?

### ISSUE THREAD

**Issue by s4il3sh** [ubsuny/23-Homework1G2#53]
@Pranjal-Srivastava-2023 @tirthbha  I sent the pull request but it is showing 1 conflict. Need to check what the issue is. So, i wanted to cancel the pull request. Any idea how to do it?

**Comment by WildJimmy** [comment]
You can do this by going to the page for the pull request, then scrolling down to the button on the comment box that says "close pull request" (I've attached a screenshot to help)
![mergecap](https://github.com/ubsuny/23-Homework1G2/assets/94491866/5006f39d-2edb-4f9e-950a-dfa4e7bc1bd4)

That said, conflicts will happen when you change parts of the code so it may just be something your maintainer has to resolve. I am the maintainer for my group and I think it's just unavoidable depending on what parts of the code you modify

**Comment by s4il3sh** [comment]
@WildJimmy Thank you that's helpful.
