### ISSUE TITLE
Can't assign Label

### ISSUE THREAD

**Issue by tirthbha** [ubsuny/23-Homework1G2#54]
@Pranjal-Srivastava-2023 @s4il3sh I am unable to assign any label to my issues. The label option, in my case, is only readable but not operable. 
How to fix this issue?
![Label_issue](https://github.com/ubsuny/23-Homework1G2/assets/143649367/bcf20d14-2c97-4dcd-b9de-538b70c1014c)

**Comment by s4il3sh** [comment]
@tirthbha maybe the maintainer didn't add you to the G2 group. I guess only @Pranjal-Srivastava-2023 can fix this by adding you to this group.

**Comment by Pranjal-Srivastava-2023** [comment]
@tirthbha this means you have not accepted the invite to G2 sent by professor. Check your inbox for the link.

**Comment by Pranjal-Srivastava-2023** [comment]
> @tirthbha maybe the maintainer didn't add you to the G2 group. I guess only @Pranjal-Srivastava-2023 can fix this by adding you to this group.

Maintainers were not able to add group members, which is why in the beginning professor sent an invite link to all.

**Comment by Pranjal-Srivastava-2023** [comment]
@tirthbha check discord. As of 15th September, you have a pending invite for G2 homework group.

**Comment by tirthbha** [comment]
> @tirthbha check discord. As of 15th September, you have a pending invite for G2 homework group.

I checked it but showing the invitation not found. I think have accepted the invitation otherwise how can I do other stuffs in the group.
