### ISSUE TITLE
Documentation Review

### ISSUE THREAD

**Issue by tirthbha** [ubsuny/23-Homework1G2#55]
@Pranjal-Srivastava-2023 I think there is a mistake in the circuit operation for 0+1. There should be 1 as a sum (from q2) and 0 as a carry (from q3)  for this operation.

**Comment by Pranjal-Srivastava-2023** [comment]
@tirthbha I will check and update it.

**Comment by s4il3sh** [comment]
@tirthbha it is ok and the documentation is updated.
