### ISSUE TITLE
Add docstring in the file - quantum_addition.py

### ISSUE THREAD

**Issue by s4il3sh** [ubsuny/23-Homework1G2#56]
@Pranjal-Srivastava-2023 @tirthbha guys we need to start adding docstring to the file. I tried doing it, it is throwing some errors and also no idea to check if my docstring is working.

**Comment by Pranjal-Srivastava-2023** [comment]
@s4il3sh quantum_addition.py already have docstring. Line 8 to 18. Are you referring to something else?

```python
    Adds two numbers using a quantum circuit:

    Args:
        num1 (int): The first number to be added.
        num2 (int): The second number to be added.
        shots (int): The number of shots (measurements) to perform.

    Returns:
        int: The sum of num1 and num2.

**Comment by Pranjal-Srivastava-2023** [comment]
@s4il3sh can you take care of issue #49 #50 #51 These 3 tasks need to be completed to achieve the milestone. You will also get points for commits. Make a separate branch, add the material to documentation.md, then send me merge request.

**Comment by s4il3sh** [comment]
@Pranjal-Srivastava-2023 sure.

Yeah, I am going to add a docstring for the line below 25. Do we need to do that or not? If we need to do then, we need to change some of our code starting from "def". This change will help us to add docstring.

**Comment by Pranjal-Srivastava-2023** [comment]
> @Pranjal-Srivastava-2023 sure.
> 
> Yeah, I am going to add a docstring for the line below 25. Do we need to do that or not? If we need to do then, we need to change some of our code starting from "def". This change will help us to add docstring.

@s4il3sh let's complete the milestone first. We have already added docstring for the initial part of the code. As the HW is due tomorrow I suggest we focus on completing the documentation.

**Comment by s4il3sh** [comment]
@Pranjal-Srivastava-2023 documentation of half-adder completed. Sent merge request. Please check.

**Comment by tirthbha** [comment]
@Pranjal-Srivastava-2023 I have added docstring to the documentation.

**Comment by Pranjal-Srivastava-2023** [comment]
> @Pranjal-Srivastava-2023 documentation of half-adder completed. Sent merge request. Please check.

@s4il3sh file merged successfully.

**Comment by Pranjal-Srivastava-2023** [comment]
> @Pranjal-Srivastava-2023 I have added docstring to the documentation.

@tirthbha there are existing conflicts.
