### ISSUE TITLE
Crack Homework Points.

### ISSUE THREAD

**Issue by s4il3sh** [ubsuny/23-Homework1G2#6]
@laserlab So far I understood that the homework points are that the more we interact in our project, we are going to earn points based on it, right? For instance, max. issue opened like - if one person opens 21 issues max, gonna earn 10.5 points, or say opens 10 issues, will earn 5 points? And so...

**Comment by Pranjal-Srivastava-2023** [comment]
Yes, we get points for interaction within our group and for interacting with the other groups as well. There are 0.5 points for opening the issue and 0.3 for closing it. The grading scheme is given in the Homework task.

**Comment by s4il3sh** [comment]
@laserlab @Pranjal-Srivastava-2023 When is the due date for the homework submission?

**Comment by Pranjal-Srivastava-2023** [comment]
@s4il3sh the due date is next Monday. We should aim to finish it by Friday 15th September.

**Comment by s4il3sh** [comment]
@Pranjal-Srivastava-2023 Got it! Thanks
