### ISSUE TITLE
Unable to merge

### ISSUE THREAD

**Issue by tirthbha** [ubsuny/23-Homework1G2#62]
![Screenshot from 2023-09-17 17-43-58](https://github.com/ubsuny/23-Homework1G2/assets/143649367/c55f2f6a-54bf-44f5-a274-b785ce607b08)
Why this conflict is showing at the time of merging request?

**Comment by Pranjal-Srivastava-2023** [comment]
@tirthbha patch1 and patch2 have conflicts, they can not be merged unless resolved. i am working on that.
