### ISSUE TITLE
Done with Unit Test

### ISSUE THREAD

**Issue by tirthbha** [ubsuny/23-Homework1G2#63]
@Pranjal-Srivastava-2023 I have done with my part and I have sent you merge request.  Please let me know if any other tasks remain to complete.

**Comment by Pranjal-Srivastava-2023** [comment]
@tirthbha I think we are almost done. No need to do anything new. Thanks!

**Comment by tirthbha** [comment]
@Pranjal-Srivastava-2023 
Great! Thank you.
