### ISSUE TITLE
No Update 

### ISSUE THREAD

**Issue by tirthbha** [ubsuny/23-Homework1G2#66]
@Pranjal-Srivastava-2023 
Have you found my merged file? I am asking because you haven't updated the documentation file that I have added. Is there any conflict from my side?

**Comment by Pranjal-Srivastava-2023** [comment]
@tirthbha Yes! the updated file has conflicts that will need to be resolved. I am trying to do that now.

**Comment by tirthbha** [comment]
> @tirthbha Yes! the updated file has conflicts that will need to be resolved. I am trying to do that now.

@Pranjal-Srivastava-2023 What about others?

**Comment by Pranjal-Srivastava-2023** [comment]
@tirthbha all 3 files patch1 patch2 and final update have conflict. I can not merge without resolving those.

**Comment by Pranjal-Srivastava-2023** [comment]
@tirthbha merged your final update. I think patch 1 is outdated now so, I will not merge it.

**Comment by tirthbha** [comment]
@ Great job

**Comment by tirthbha** [comment]
> @tirthbha merged your final update. I think patch 1 is outdated now so, I will not merge it.

Its okay.

**Comment by Pranjal-Srivastava-2023** [comment]
> > @tirthbha merged your final update. I think patch 1 is outdated now so, I will not merge it.
> 
> Its okay. Can I delete this patch 1?

I have closed the pull request for patch 1. Great job from your side!
