### ISSUE TITLE
Arithmetic function for the homework G4

### ISSUE THREAD

**Issue by yasmensarhan27** [ubsuny/23-Homework1G2#7]
Hi There, 

this is to let you know that we, in G4, have chosen the multiplication function for our homework.
 
Please let us know the arithmetic function you've chosen. 

Good Luck

**Comment by Pranjal-Srivastava-2023** [comment]
Hi @yasmensarhan27 , that's good to know. We in G2 will probably choose either addition or subtraction. Good luck to you too!
