### ISSUE TITLE
Mismatch at the end!

### ISSUE THREAD

**Issue by tirthbha** [ubsuny/23-Homework1G2#71]
@Pranjal-Srivastava-2023 
Please have a look at the end part of documentation. The explanation of circuit operation for 0+1 is copied for 1+0.

**Comment by Pranjal-Srivastava-2023** [comment]
@tirthbha Yes! they are the same. Why is that? It needs to be corrected.

**Comment by s4il3sh** [comment]
@tirthbha please correct it, I didn't read that at all. I saw your explanation of the limitation part so i copied and pasted it. Also, please write an explanation for 0+0. It is the only one left in the documentation.

**Comment by tirthbha** [comment]
@s4il3sh @Pranjal-Srivastava-2023 
No there are two parts remain to explain i.e. 1+0 and 0+0. However, the circuits are different from those of 1+1 and 0+1. I think it is better to write "similarly ... 1+0 and 0+0 works" at the bottom of the circuits.

**Comment by tirthbha** [comment]
> @tirthbha Yes! they are the same. Why is that? It needs to be corrected.

@Pranjal-Srivastava-2023 But in my branch there is no such copy.
