### ISSUE TITLE
Change required

### ISSUE THREAD

**Issue by tirthbha** [ubsuny/23-Homework1G2#72]
The code in the quantum_addition.py doesn't match with that on the documentation file, as there are more comments in the .py file. Please fix that change. @Pranjal-Srivastava-2023

**Comment by s4il3sh** [comment]
@tirthbha please mention line number to be exact.

**Comment by tirthbha** [comment]
> @tirthbha please mention line number to be exact.

Better to make change with the entire code.
@s4il3sh

**Comment by Pranjal-Srivastava-2023** [comment]
@tirthbha @s4il3sh I will fix that.
