### ISSUE TITLE
Trial code for addition to be run on IBM Quantum Lab.

### ISSUE THREAD

**Issue by Pranjal-Srivastava-2023** [ubsuny/23-Homework1G2#8]
Run this code on IBM Quantum Lab using different numbers each time and see where it fails.

```python
from qiskit import QuantumCircuit, transpile, Aer, execute

# Define the classical numbers to be added
number1 = 30
number2 = 2

# Determine the number of qubits needed to represent the numbers
max_value = max(number1, number2)
num_qubits = max(1, (max_value.bit_length() + 1))

# Create a quantum circuit with enough qubits
qc = QuantumCircuit(num_qubits * 2, num_qubits)

# Encode the classical numbers into quantum states
for i in range(num_qubits):
    if (number1 >> i) & 1:
        qc.x(i)  # Apply X gate for 1 bits in number1
    if (number2 >> i) & 1:
        qc.x(i + num_qubits)  # Apply X gate for 1 bits in number2

# Perform the addition by applying CNOT gates
for i in range(num_qubits - 1):
    qc.ccx(i, i + num_qubits, i + num_qubits + 1)
    qc.cx(i, i + num_qubits)

# Measure the result
qc.measure(range(num_qubits, num_qubits * 2), range(num_qubits))

# Simulate the circuit
simulator = Aer.get_backend('qasm_simulator')
compiled_circuit = transpile(qc, simulator)
job = execute(compiled_circuit, simulator, shots=1)
result = job.result()

# Get the measurement result
counts = result.get_counts(qc)
result_decimal = int(list(counts.keys())[0], 2)

# Print the result
print(f"The result of {number1} + {number2} is {result_decimal}")
```

**Comment by Pranjal-Srivastava-2023** [comment]
I have also added "Trial code-1.py" in the repository. @s4il3sh @tirthbha you can fork it from the main branch and make any changes and commit. Then send me a merge request. It is part of the homework.

**Comment by Pranjal-Srivastava-2023** [comment]
I have uploaded "Building a half adder circuit.ipynb" in the repository. Please have a look, it is similar to what we discussed in class. We can use IBM Quantum Composer to make these circuits and perform quantum addition.

**Comment by tirthbha** [comment]
> I have uploaded "Building a half adder circuit.ipynb" in the repository. Please have a look, it is similar to what we discussed in class. We can use IBM Quantum Composer to make these circuits and perform quantum addition. Credits to: http://www.qmunity.tech/

Yeah! this is almost similar to the class work. I think we should go for it. Let us understand this circuit thoroughly, then we will decide our job for the assignment.
