### ISSUE TITLE
Unit test file added

### ISSUE THREAD

**Issue by Pranjal-Srivastava-2023** [ubsuny/23-Homework1G2#89]
@tirthbha @s4il3sh We had to add a separate file for the unit test. I have added that now. Check it out.

**Comment by tirthbha** [comment]
@Pranjal-Srivastava-2023 Have you omitted the figures and explanations of 0+0 and 1+0 from the documentation?

**Comment by Pranjal-Srivastava-2023** [comment]
@tirthbha yes! it looked too cluttered and the images were of different sizes and resolutions.
